"""Typed data contracts for LLM extraction outputs.

This module defines the strict schema used at the boundary between the
probabilistic extractor (LLM) and the deterministic legal logic graph.
"""

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class ContractType(str, Enum):
	"""Allowed legal document categories supported by the PoC.

	Restricting contract type to a closed set prevents downstream logic from
	receiving unsupported categories inferred by the LLM.
	"""

	NDA = "NDA"
	SERVICES = "SERVICES"


class Jurisdiction(str, Enum):
	"""Allowed governing-law jurisdictions for the PoC rule set.

	The decision graph is intentionally limited to this legal domain. Any value
	outside this enum (for example, "Narnia") is rejected at validation time.
	"""

	NY = "NY"
	CA = "CA"
	DELAWARE = "DELAWARE"


class ContractData(BaseModel):
	"""Normalized clauses extracted from a contract document.

	This model is the single source of truth for data entering deterministic
	reasoning. Validation failures are expected and desirable when extraction
	output is incomplete, inconsistent, or outside policy constraints.

	Attributes:
		contract_type: Legal document category constrained by `ContractType`.
		governing_jurisdiction: Governing-law jurisdiction constrained to the
			approved enum domain.
		effective_date: Contract start date from the signed text.
		explicit_expiration_date: Date where the contract states explicit
			expiration. Optional because some agreements only define duration.
		auto_renewal: Indicates whether the contract auto-renews.
		non_renewal_notice_days: Notice period required to prevent renewal.
		has_arbitration_clause: Indicates whether arbitration is required.
		liability_cap_amount: Monetary cap for total liability when specified.
			`None` means no explicit numeric cap was extractable.
		indemnification_uncapped: Whether indemnification is explicitly uncapped.
		confidentiality_survival_years: Post-termination confidentiality period.
		trade_secret_survival_years: Post-termination trade-secret period.
	"""

	model_config = ConfigDict(
		extra="forbid",
		strict=True,
		str_strip_whitespace=True,
		frozen=True,
	)

	contract_type: ContractType = Field(
		...,
		description=(
			"Closed legal category used by routing logic to select the correct "
			"decision graph branch."
		),
	)
	governing_jurisdiction: Jurisdiction = Field(
		...,
		description=(
			"Governing-law clause normalized to an allowed enum value; invalid "
			"or hallucinated jurisdictions must be rejected."
		),
	)
	effective_date: date = Field(
		...,
		description="Execution/effective date that anchors temporal obligations.",
	)
	explicit_expiration_date: date | None = Field(
		default=None,
		description=(
			"Explicit contract expiration date when present in text. This can "
			"coexist with renewal clauses and is later reconciled by logic."
		),
	)
	auto_renewal: bool = Field(
		...,
		description="Whether the agreement renews automatically absent notice.",
	)
	non_renewal_notice_days: int | None = Field(
		default=None,
		ge=0,
		description=(
			"Minimum notice days required to stop renewal. Optional when no "
			"renewal clause is present."
		),
	)
	has_arbitration_clause: bool = Field(
		...,
		description=(
			"Boolean marker used by dispute-resolution policy checks in the "
			"deterministic graph."
		),
	)
	liability_cap_amount: float | None = Field(
		default=None,
		gt=0,
		description=(
			"Numeric liability cap extracted from limitation-of-liability "
			"language. `None` if no cap is clearly defined."
		),
	)
	indemnification_uncapped: bool = Field(
		...,
		description=(
			"True when indemnification obligations are explicitly uncapped, a "
			"high-risk legal signal."
		),
	)
	confidentiality_survival_years: int | None = Field(
		default=None,
		ge=0,
		description=(
			"Number of years confidentiality obligations survive after "
			"termination."
		),
	)
	trade_secret_survival_years: int | None = Field(
		default=None,
		ge=0,
		description=(
			"Number of years trade-secret obligations survive after disclosure "
			"or termination, depending on clause wording."
		),
	)


class EvaluationReport(BaseModel):
	"""Deterministic legal evaluation output generated by the logic graph.

	Attributes:
		is_approved: Global approval flag. `True` only when no red flags exist.
		flags_rojas: List of blocking findings that require rejection or legal
			escalation before approval.
		advertencias: List of non-blocking findings for analyst visibility and
			follow-up.
	"""

	model_config = ConfigDict(
		extra="forbid",
		strict=True,
		str_strip_whitespace=True,
		frozen=True,
	)

	is_approved: bool = Field(
		...,
		description="Overall deterministic verdict for the evaluated contract.",
	)
	flags_rojas: list[str] = Field(
		default_factory=list,
		description=(
			"Blocking legal findings that violate policy thresholds or mandatory "
			"controls."
		),
	)
	advertencias: list[str] = Field(
		default_factory=list,
		description=(
			"Non-blocking findings that should be reviewed by legal or compliance."
		),
	)
